author: Nadri
title: Nadri's musings
repository: Nadrieril/blog
url: https://nadrieril.github.io
baseurl: /blog

markdown: GFM

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gfm-admonitions

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post-with-toc"

# Use upstream minima instead of GitHub Page's outdated version.
remote_theme: jekyll/minima
